Algoritmo "semnome"

Var
filme : inteiro

Inicio
escreval ("HORÁRIO DE EXIBIÇÃO")
escreval ("")

escreval ("Escolha uma das opções de filme: ")
escreval ("1 - Estômago")
escreval ("2 - Top Gun")
leia (filme)

escolha filme

caso 1
escreval ("Horário de exibição de Estômago é 18:30")

caso 2
escreval ("Horário de exibição de Top Gun é 15:00")

outrocaso
escreval ("Opção de filme inválida")

fimescolha

Fimalgoritmo